README.md

The instructions on Getting Binaries seemed to be out of date. Updated it to be consistent with the scodec-scalaz repo.

Update Getting Binaries to be consistent

---

CHANGELOG.md
benchmark/src/main/scala/NumericConversionBenchmarks.scala
core/shared/src/main/scala/scodec/bits/BitVector.scala

`run -i 10 -wi 10 -f1 -t1 .*NumericConv.*`
```
[info] Benchmark                                                          Mode  Cnt    Score    Error  Units
[info] NumericConversionBenchmarks.fromInt_16bit_bigEndian                avgt   10  146.476 ±  7.589  us/op
[info] NumericConversionBenchmarks.fromInt_30bit_bigEndian                avgt   10  135.761 ± 10.377  us/op
[info] NumericConversionBenchmarks.fromInt_30bit_littleEndian             avgt   10  285.830 ± 20.083  us/op
[info] NumericConversionBenchmarks.fromInt_32bit_bigEndian                avgt   10   43.472 ±  3.357  us/op
[info] NumericConversionBenchmarks.fromInt_32bit_littleEndian             avgt   10   48.617 ±  2.885  us/op
[info] NumericConversionBenchmarks.toInt_14bit_bigEndian                  avgt   10   44.556 ± …
```

Improve performance of numeric conversions

---

core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/BitVectorTest.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

The == method now delegates through to === when the types match.

Add type-safe === to BitVector and ByteVector

---

core/jvm/src/test/scala/scodec/bits/ByteVectorJvmTest.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

Previously if you passed `nowrap = true` to deflate, then calling
inflate would fail because `nowrap` would default to false, but the
header and checksum would be present.
Note: the `ZlibCodec.decode` method in scodec-core should also respect the `nowrap` param. I'm happy to make that change, but I assume it will have to wait until the master branch of scodec is depending on a version of scodec-bits that has this change?

Take nowrap param in inflate

---

benchmark/src/main/scala/ScodecBitsBenchmark.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

With 1.0.10-SNAPSHOT and no changes:
```
[info] Benchmark                           Mode  Cnt     Score    Error  Units
[info] ScodecBitsBenchmark.fromBase64      avgt   10  1280.137 ± 31.007  us/op
[info] ScodecBitsBenchmark.fromBase64_JRE  avgt   10     3.754 ±  0.162  us/op
```
With changes:
```
[info] Benchmark                           Mode  Cnt  Score   Error  Units
[info] ScodecBitsBenchmark.fromBase64      avgt   10  5.654 ± 0.333  us/op
[info] ScodecBitsBenchmark.fromBase64_JRE  avgt   10  3.790 ± 0.167  us/op
```

Improve performance of ByteVector.fromBase64

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala

Scalac supports treating SAM types (aka functional interfaces) as
functions types. To date, this has only been enabled under
-Xexperimental, but it is intended to be enabled by default in Scala
2.12.
This isn't a strictly source compatble change the compiler.
For example, it can make more overloaded alternatives feasible, which
hampers parameter type inferences in the arguments to an call.
That happens with the overloads on `ByteVector.view`. This commit
explicitly specifies the anonymous function parameter type to work
under both the old and new regimes.
Here's the [failed community build](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/250/consoleFull) in which I tried to enable SAM support
by default:
```
[scodec-bits] [error] …
```

Support compilation under -Xexperimental

---

core/shared/src/main/scala/scodec/bits/BitVector.scala

In 2.12, and 2.11 -Xexperimental, SAM types compete
with FunctionN types, which breaks type inference
during overloading resolution when both the SAM and
FunctionN alternatives apply.
See also #44

Future-proof for Scala 2.12 re: SAM support

---

build.sbt

The original issue seems to be solved[1, 2].
Additionally, as ktoso says, it'd be nice for us to upgrade sbt-jmh to the newer version.[1]
[1] https://github.com/ktoso/sbt-jmh/issues/76#issuecomment-247279609
[2] https://github.com/retronym/scala-jmh-suite/commit/cd281784250d9fdcd4306150873803481fa039e9
P.S.
BTW, I opened a PR to upgrade sbt-jmh :)
https://github.com/scodec/scodec-build/pull/1

Remove unnecessary workaround for sbt-jmh cross compile

---

core/jvm/src/test/scala/scodec/bits/ByteVectorJvmTest.scala
core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

Updated the comments for the ByteVector and BitVector versions of the functions fromBase64, fromValidBase64, and fromBase64Descriptive. Added a test for an empty input string. Added a few more padding and non-divisible by 4 tests.

Issue #76: Added tests and updated the comments for ByteVector and BitVector

---

core/shared/src/main/scala/scodec/bits/BitVector.scala

https://github.com/scala/scala/commit/8ae50c164565332d2059e2718a901dd4a591617b

fix warning. shifting a value by a Long argument is deprecated

---

core/shared/src/main/scala/scodec/bits/BitVector.scala

Believe somebody had previously requested this on Gitter and I found myself also scratching my head at the error messages recently, so they are now a little more verbose. "Trying to left-pad a vector of 96 bits to 64 bits."

Make padLeft/Right errors more verbose.

---

.gitignore
core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/BitVectorTest.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Fix for #55 -- `grouped` should return an `Iterator` instead of a `Stream`.

Fixed #55 by deprecating grouped and replacing with groupedI

---

core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/test/scala/scodec/bits/BitVectorTest.scala

BitVector.toLong was failing to decode large negative longs not encoded in 64 bits because the test on the sign was between an Int and Long, the shift was not triggered. 
correction and test in commit

BitVector.toLong for signed negative from 33 to 63 bits

---

core/shared/src/main/scala/scodec/bits/Bases.scala
core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

This PR adds base32 support as in https://tools.ietf.org/html/rfc4648#section-6.

Base32 support

---

core/shared/src/main/scala/scodec/bits/Bases.scala
core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

The base32 alphabet from my last PR is a bit too relaxed, allows lowercase characters and automatically parses a zero as an 'o'.
This is the right thing to do for the crockford alphabet but it is not permitted for the RFC one which is far more strict.
The crockford alphabet also allows '-' as an ignored character which the RFC doesn't allow.
I added tests to verify this behaviour.
Also I added the missing "fromBase32..." methods to BitVector.

Base32 RFC 4648 conformity

---

core/jvm/src/test/scala/scodec/bits/ByteVectorJvmTest.scala
core/shared/src/main/scala/scodec/bits/Bases.scala
core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

Also adds support for `0.toChar` as indicating no padding which wasn't consistent in all of the base* helpers.

Base64 NoPad/Url options -  1.1.x

---

.travis.yml
build.sbt
core/shared/src/main/scala-2.11/scodec/bits/ScalaVersionSpecific.scala

`crossScalaVersions := Seq("2.11.12", "2.12.11", "2.13.2"),`
```
$ sbt +test
[info] Run completed in 1 minute, 55 seconds.
[info] Total number of tests run: 129
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 129, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 129, Failed 0, Errors 0, Passed 129
[success] Total time: 208 s (03:28), completed Jun 17, 2020, 10:33:26 AM
```

Add Scala 2.11.x support - 1.1.x

---

core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/BitVectorTest.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Steps towards https://github.com/scodec/scodec-cats/issues/13
/cc @mpilquist

Implement `Ordered` interface in ByteVector and BitVector

---

core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

@mpilquist wouldn't this be more efficient implementation of `equals`?

Optimize BitVector's and ByteVector's equals

---

core/shared/src/main/scala/scodec/bits/Bases.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Because `U` was mixed into the chars used by `Base32Crockford`, both encoding and decoding of strings containing symbols later `V` were broken.
This commit fix the problem, and add a simple test to check the correspondence of Strings with Bytes in typical cases.

Fix Base32Crockford symbols

---

core/shared/src/main/scala/scodec/bits/BitVector.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala

workaround for https://github.com/scala/bug/issues/12137

override foldRight on BitVector/ByteVector

---

core/shared/src/main/scala-2/scodec/bits/package.scala

this future-proofs the code for scala/scala#9303,
and IMO the new code is just as good anyway

avoid using type parameters on Left or Right

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Hello,
I needed to convert the `ByteVector` to `InputStream` and surprisingly, that is not supported yet. Here is the implementation so everyone could use that.

ByteVector.toInputStream method

---

core/js/src/main/scala/scodec/bits/ByteVectorCompanionCrossPlatform.scala
core/js/src/main/scala/scodec/bits/ByteVectorCrossPlatform.scala
core/js/src/test/scala/scodec/bits/ByteVectorJsTest.scala

Every JS API I've worked with uses `Uint8Array` type to represent byte vectors, which I'm guessing is how these conversions will be used 99% of the time. Also adjusted method names to avoid ambiguity.

Use `Uint8Array` instead of `Int8Array` for JS interop

---

core/js/src/main/scala/scodec/bits/ByteVectorCrossPlatform.scala

Should have PR'd a bit earler ;)
Adds a few converters to `js.ArrayBuffer` I missed on the first pass, really just spare some minor inconvenience for users.

Add converters to `js.ArrayBuffer`

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Fixes https://github.com/scodec/scodec-bits/issues/369
`read()` should return a value between 0 and 255 (https://docs.oracle.com/javase/9/docs/api/java/io/InputStream.html#read--)

read() in inputstream should return unsigned value

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala

This PR adds `toHexDump` to `ByteVector` as well as adding a flexible `ByteVector.HexDumpFormat` type with various formatting options.
The default hex dump is modeled after the Linux `hexdump -C` command but colorizes the output.

Add support for generating hex dumps

---

build.sbt
core/shared/src/main/scala/scodec/bits/HexDumpFormat.scala

This PR re-implements hex dumps to allow for constant memory streaming of suspended `BitVector`s. It uses the same technique as `StreamingBitVectorTest`, where care is taken to ensure we don't hold on to a `BitVector` that later is forced by iteration.

Support streaming hex dumps

---

core/shared/src/main/scala-2/scodec/bits/LiteralSyntaxMacros.scala
core/shared/src/main/scala-2/scodec/bits/package.scala
core/shared/src/main/scala-3/scodec/bits/Interpolators.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Wanted these at least a few times :)
```
scala> val b = ascii"deadbeef"
val b: scodec.bits.ByteVector = ByteVector(8 bytes, 0x6465616462656566)
```
```
scala> val b = utf8"ɟǝǝqpɐǝp"
val b: scodec.bits.ByteVector = ByteVector(13 bytes, 0xc99fc79dc79d7170c990c79d70)
```

Add ascii and utf8 interpolators

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala

This PR add a minor optimization to two `++` methods to avoid creating a new `Append` node if one of the ByteVectors is empty.

Add `isEmpty` shortcuts to `++` methods

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

Add ByteVector#toArrayUnsafe - a zero-copy version of toArray

---

benchmark/src/main/scala/ByteVectorBenchmark.scala
core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

- Remove use of StringBuilder
- Add a special case for arrays
These changes result in a ~4x improvement on array backed byte vectors and should have no penalty for non-array vectors.

Optimize toHex

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

1. `toByteBuffer` should only return a read-only buffer if necessary to protect its internals. Read-only buffers don't allow access to the underlying array which can force further copies downstream. If the data is already being copied, then there is no reason to return a read-only buffer.
2. Add `toByteBufferUnsafe`. In the spirit of `toArrayUnsafe`, but can avoid copies in several more situations e.g. a view of a slice of an array. This will enable copy-free transforms to `Chunk.ArraySlice` in FS2.

`toByteBuffer` optimizations

---

core/shared/src/main/scala/scodec/bits/ByteVector.scala
core/shared/src/test/scala/scodec/bits/ByteVectorTest.scala

So that its position / limit are independent.
https://github.com/scodec/scodec-bits/blob/0b7a1aff2e52c875aceaf28c481ae12723e55fba/core/shared/src/main/scala/scodec/bits/ByteVector.scala#L770-L776

Duplicate buffer in `asByteBufferUnsafe`
